### ISSUE TITLE
Idea: memoized "current" function?

### ISSUE THREAD

**Issue by martinhynar** [dsabanin/clj-pid#1]
Thanks or this simple yet handy lib!

I was looking at the code and it just popped in my mind that the `current` function could be perhaps memoized. Assuming that PID of the process won't change, asking JMX for PID just once is enough. What do you think?

**Comment by dsabanin** [comment]
Yeah, that's a great idea. Pull requests are very welcome :)

**Comment by dsabanin** [comment]
Thanks!
